CREATE schema IF NOT EXISTS zerno;

create table IF NOT EXISTS zerno.bonus (
    id int4 generated by default as identity,
    bonuses int4,
    first_name varchar(255),
    last_name varchar(255),
    phone varchar(255),
    primary key (id)
);

create table IF NOT EXISTS zerno.staff (
    id int4 generated by default as identity,
     address varchar(255),
      first_name varchar(255),
      last_name varchar(255),
      phone_id int4 not null,
      position varchar(255),
      salary float8,
      primary key (id)
);

create table IF NOT EXISTS zerno.phone (
    id int generated by default as identity,
    number varchar(255),
    primary key (id)
);

ALTER table zerno.staff
    ADD CONSTRAINT fk_phone_number
        FOREIGN KEY (id)
            REFERENCES zerno.phone (id);